name: build-artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.47.1'
  GO_VERSION: '1.26.4'
  NDK_VERSION: r28c

jobs:
  build:
    name: ${{ matrix.platform }}${{ matrix.arch && format('-{0}', matrix.arch) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
          - platform: windows
            os: windows-2022
            arch: amd64
          - platform: linux
            os: ubuntu-22.04
            arch: amd64
          - platform: macos
            os: macos-15-intel
            arch: amd64
          - platform: macos
            os: macos-latest
            arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: core/go.sum

      - name: Setup Java
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        if: matrix.platform == 'android'
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            services/helper
            plugins/rust_api/rust
          cache-directories: .dart_tool/hooks_runner

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Setup Xcode
        if: matrix.platform == 'macos'
        run: |
          sudo xcode-select -s /Applications/Xcode_26.3.app || sudo xcode-select -s /Applications/Xcode_26.2.app
          xcodebuild -version

      - name: Setup NDK
        if: matrix.platform == 'android'
        uses: nttld/setup-ndk@v1
        id: build-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: true
          link-to-sdk: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build packages
        shell: bash
        env:
          ANDROID_NDK_HOME: ${{ steps.build-ndk.outputs.ndk-path }}
        run: |
          if [[ "${{ matrix.platform }}" == "android" ]]; then
            dart setup.dart android --env pre --verbose
          else
            dart setup.dart "${{ matrix.platform }}" --env pre --verbose
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FlClash-${{ matrix.platform }}${{ matrix.arch && format('-{0}', matrix.arch) }}
          path: dist/
          if-no-files-found: error
